# Generated by Django 5.2.6 on 2026-07-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='rating',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
